"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import json
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

def _csv(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# Comma-separated public host names for the live site, for example
# "risemorgan.org,www.risemorgan.org". Local development hosts are always allowed.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] + _csv('ALLOWED_HOSTS')
# Needed for sign-in forms when the site sits behind HTTPS, for example
# "https://risemorgan.org".
CSRF_TRUSTED_ORIGINS = _csv('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.microsoft',
    'members',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'members.context_processors.sso_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite is for local development only. Set DATABASE_URL to a PostgreSQL URL
# (postgres://user:password@host:5432/name) for any site holding real scholar data.
_database_url = os.getenv('DATABASE_URL', '')
if _database_url:
    from urllib.parse import unquote, urlparse
    _db = urlparse(_database_url)
    if _db.scheme not in ('postgres', 'postgresql'):
        raise ValueError('DATABASE_URL must be a PostgreSQL URL.')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote(_db.path.lstrip('/')),
            'USER': unquote(_db.username or ''),
            'PASSWORD': unquote(_db.password or ''),
            'HOST': _db.hostname or '',
            'PORT': _db.port or '',
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# The President asked for no password rules beyond a basic length floor (September 30).
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Production transport security. Only relaxed while DEBUG is on for local work.
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Set to "HTTP_X_FORWARDED_PROTO" only when the host's proxy sets that header.
    if os.getenv('RISE_PROXY_SSL_HEADER'):
        SECURE_PROXY_SSL_HEADER = (os.getenv('RISE_PROXY_SSL_HEADER'), 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = "/portal/"
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Microsoft Entra credentials belong in .env or the deployment secret store.
# The callback to register with Entra is /accounts/microsoft/login/callback/.
MICROSOFT_CLIENT_ID = os.getenv('MICROSOFT_CLIENT_ID', '')
MICROSOFT_CLIENT_SECRET = os.getenv('MICROSOFT_CLIENT_SECRET', '')
MICROSOFT_TENANT_ID = os.getenv('MICROSOFT_TENANT_ID', '')
RISE_MICROSOFT_SSO_ENABLED = all((
    MICROSOFT_CLIENT_ID,
    MICROSOFT_CLIENT_SECRET,
    MICROSOFT_TENANT_ID,
))

SOCIALACCOUNT_ADAPTER = 'members.adapters.RISESocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = False
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_LOGIN_ON_PASSWORD_RESET = False
ACCOUNT_ADAPTER = 'members.adapters.RISEAccountAdapter'
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

# Keep licensed source material outside version control.
# See docs/backend-fixes.md for the configuration format.
_intake_config_path = os.getenv('RISE_INTAKE_CONFIG', '')
if _intake_config_path:
    with open(_intake_config_path, encoding='utf-8-sig') as _intake_file:
        _intake_config = json.load(_intake_file)
else:
    _intake_config = {}
RISE_AGREEMENTS = _intake_config.get('agreements', {})
RISE_REFLECTION_ITEMS = _intake_config.get('reflection_items', [])
RISE_PARTNER_URL = os.getenv('RISE_PARTNER_URL', '')
# Where the Give button sends people (for example a Morgan giving page or a fiscal sponsor).
# The website itself never takes payments.
RISE_DONATE_URL = os.getenv('RISE_DONATE_URL', '')
RISE_CONTACT_EMAIL = os.getenv('RISE_CONTACT_EMAIL', '')
# The public address of the site, used for links inside emails, for example https://risemorgan.org
RISE_SITE_URL = os.getenv('RISE_SITE_URL', '')
# Key for encrypting sensitive fields. Generate once with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# and keep it in the host's secret store. Losing it means those fields cannot be read again.
RISE_FIELD_KEY = os.getenv('RISE_FIELD_KEY', '')
RISE_MENTOR_APPLY_URL = os.getenv('RISE_MENTOR_APPLY_URL', '')
# Outside sites a link code may open without approval (the IT Director keeps this list, Overview 9.5).
RISE_LINK_ALLOWLIST = [d.strip().lower() for d in os.getenv(
    'RISE_LINK_ALLOWLIST', 'morgan.edu,forms.gle,docs.google.com,forms.office.com,instagram.com').split(',') if d.strip()]
RISE_CONCERN_RECIPIENT_EMAILS = [email.strip().lower() for email in
    os.getenv('RISE_CONCERN_RECIPIENT_EMAILS', '').split(',') if email.strip()]
RISE_CONCERN_MIN_LENGTH = 20
RISE_CONCERN_RATE_LIMIT = 5  # per browser, per hour
# Campus wifi shares a few addresses, so the per-address ceiling is much higher.
RISE_CONCERN_ADDRESS_LIMIT = 60
# The header the host's proxy sets with the real visitor address, for example
# "HTTP_X_FORWARDED_FOR", and how many trusted proxies append to it.
RISE_CLIENT_IP_HEADER = os.getenv('RISE_CLIENT_IP_HEADER', '')
RISE_TRUSTED_PROXY_COUNT = int(os.getenv('RISE_TRUSTED_PROXY_COUNT', '1'))
RISE_CONCERN_RATE_SECONDS = 3600
RISE_OPERATIONS_ALERT_EMAILS = [email.strip() for email in
    os.getenv('RISE_OPERATIONS_ALERT_EMAILS', '').split(',') if email.strip()]
SOCIALACCOUNT_PROVIDERS = {
    'microsoft': {
        'APPS': ([{
            'client_id': MICROSOFT_CLIENT_ID,
            'secret': MICROSOFT_CLIENT_SECRET,
            'settings': {'tenant': MICROSOFT_TENANT_ID},
        }] if RISE_MICROSOFT_SSO_ENABLED else []),
        'SCOPE': ['openid', 'profile', 'email'],
    },
}
